const commandMap = {
    ///// Buka Aplikasi /////
    "open_word": "start winword",
    "open_excel": "start excel", 
    "open_powerpoint": "start powerpnt",
    "open_outlook": "start outlook",
    "open_steam": "start steam",
    "open_spotify": "start spotify",
    "open_discord": "start discord",
    "open_zoom": "start zoom",
    "open_photoshop": "start photoshop",
    "open_adobe": "start acrobat",
    "open_vlc": "start vlc",
    "open_7zip": "start 7zFM",
    "open_obs": "start obs64",
    "open_blender": "start blender",
    "open_premiere": "start premiere",
    "open_aftereffects": "start afterfx",
    "open_illustrator": "start illustrator",
    "open_audacity": "start audacity",
    "open_gimp": "start gimp",
    "open_skype": "start skype",
    "open_teams": "start teams",
    
    ///// Buka Browser & Web /////
    "open_edge": "start msedge",
    "open_chrome": "start chrome",
    "open_firefox": "start firefox",
    "open_gmail": "start msedge https://mail.google.com",
    "open_drive": "start msedge https://drive.google.com",
    "open_github": "start msedge https://github.com",
    "open_youtube": "start msedge https://youtube.com",
    "open_netflix": "start msedge https://netflix.com",
    "open_whatsapp": "start msedge https://web.whatsapp.com",
    "open_facebook": "start msedge https://facebook.com",
    "open_twitter": "start msedge https://twitter.com",
    "open_instagram": "start msedge https://instagram.com",
    "open_linkedin": "start msedge https://linkedin.com",
    "open_maps": "start msedge https://maps.google.com",
    "open_translate": "start msedge https://translate.google.com",
    "open_classroom": "start msedge https://classroom.google.com",
    "open_meet": "start msedge https://meet.google.com",
    
    ///// Sistem & Utilitas /////
    "shutdown": "shutdown /s /t 1",
    "restart": "shutdown /r /t 1",
    "sleep": "rundll32.exe powrprof.dll,SetSuspendState 0,1,0",
    "hibernate": "shutdown /h",
    "lock": "rundll32.exe user32.dll,LockWorkStation",
    "open_taskmgr": "taskmgr",
    "open_controlpanel": "control",
    "open_devmgmt": "devmgmt.msc",
    "open_diskcleanup": "cleanmgr",
    "open_services": "services.msc",
    "open_eventviewer": "eventvwr.msc",
    "open_regedit": "regedit",
    "open_sysconfig": "msconfig",
    "open_diskmgmt": "diskmgmt.msc",
    "open_defragment": "dfrgui",
    "open_firewall": "control firewall.cpl",
    "open_systeminfo": "msinfo32",
    "check_windows_update": "start ms-settings:windowsupdate",
    "clear_temp": "cleanmgr /sagerun:1",
    "sfc_scan": "sfc /scannow",
    "chkdsk": "chkdsk /f",
    "battery_report": "powercfg /batteryreport",
    "power_efficiency": "powercfg /energy",
    "system_restore": "rstrui.exe",
    "disk_cleanup": "cleanmgr /sageset:1",
    "memory_diagnostic": "mdsched.exe",
    "system_properties": "sysdm.cpl",
    "device_pairing": "ms-settings:bluetooth",
    "windows_security": "windowsdefender:",
    "storage_settings": "ms-settings:storagesense",
    "backup_settings": "ms-settings:backup",
    
    ////// Network //////
    "ipconfig": "ipconfig /all",
    "ping_google": "ping 8.8.8.8",
    "flush_dns": "ipconfig /flushdns",
    "network_reset": "netsh winsock reset",
    "release_ip": "ipconfig /release",
    "renew_ip": "ipconfig /renew",
    "network_status": "netstat -an",
    "wifi_profiles": "netsh wlan show profiles",
    "wifi_password": "netsh wlan show profile name=* key=clear",
    "traceroute": "tracert 8.8.8.8",
    "network_adapters": "netsh interface show interface",
    "dns_status": "ipconfig /displaydns",
    "route_table": "route print",
    "network_shares": "net share",
    "network_statistics": "netstat -e -s",
    
    ////// File Explorer //////
    "open_documents": "start %USERPROFILE%\\Documents",
    "open_downloads": "start %USERPROFILE%\\Downloads",
    "open_desktop": "start %USERPROFILE%\\Desktop",
    "open_pictures": "start %USERPROFILE%\\Pictures",
    "open_music": "start %USERPROFILE%\\Music",
    "open_videos": "start %USERPROFILE%\\Videos",
    "open_root": "start \\",
    "open_cdrive": "start C:\\",
    "open_network": "start \\\\localhost",
    "open_3dobjects": "start %USERPROFILE%\\3D Objects",
    "open_appdata": "start %APPDATA%",
    "open_programfiles": "start C:\\Program Files",
    "open_programfilesx86": "start C:\\Program Files (x86)",
    "open_startup": "start shell:startup",
    "open_recent": "start shell:recent",
    
    ////// Aplikasi Windows //////
    "open_chrome": "start chrome",
    "open_firefox": "start firefox",
    "open_edge": "start msedge",
    "open_vscode": "start code",
    "open_notepad": "start notepad",
    "open_calculator": "start calc",
    "open_paint": "start mspaint",
    "open_cmd": "start cmd",
    "open_powershell": "start powershell",
    "open_wmp": "start wmplayer",
    "open_stickynotes": "start sticky notes",
    "open_snippingtool": "start snippingtool",
    "open_remotedesktop": "start mstsc",
    "open_defender": "start windowsdefender:",
    "open_wordpad": "start wordpad",
    "open_magnifier": "start magnify",
    "open_narrator": "start narrator",
    "open_osk": "start osk",
    "open_charactermap": "start charmap",
    
    ///// Tutup Aplikasi /////
    "close_chrome": "taskkill /IM chrome.exe /F",
    "close_firefox": "taskkill /IM firefox.exe /F", 
    "close_edge": "taskkill /IM msedge.exe /F",
    "close_word": "taskkill /IM winword.exe /F",
    "close_excel": "taskkill /IM excel.exe /F",
    "close_powerpoint": "taskkill /IM powerpnt.exe /F",
    "close_outlook": "taskkill /IM outlook.exe /F",
    "close_steam": "taskkill /IM steam.exe /F",
    "close_spotify": "taskkill /IM spotify.exe /F",
    "close_discord": "taskkill /IM discord.exe /F",
    "close_zoom": "taskkill /IM zoom.exe /F",
    "close_photoshop": "taskkill /IM photoshop.exe /F",
    "close_adobe": "taskkill /IM acrobat.exe /F",
    "close_vlc": "taskkill /IM vlc.exe /F",
    "close_7zip": "taskkill /IM 7zFM.exe /F",
    "close_obs": "taskkill /IM obs64.exe /F",
    "close_vscode": "taskkill /IM code.exe /F",
    "close_notepad": "taskkill /IM notepad.exe /F",
    "close_calculator": "taskkill /IM calculator.exe /F",
    "close_paint": "taskkill /IM mspaint.exe /F",
    "close_cmd": "taskkill /IM cmd.exe /F",
    "close_powershell": "taskkill /IM powershell.exe /F",
    "close_wmp": "taskkill /IM wmplayer.exe /F",
    "close_stickynotes": "taskkill /IM stickyNot.exe /F",
    "close_snippingtool": "taskkill /IM snippingtool.exe /F",
    "close_remotedesktop": "taskkill /IM mstsc.exe /F",
    "close_defender": "taskkill /IM msmpeng.exe /F",
    "close_all_browsers": "taskkill /IM chrome.exe /F & taskkill /IM firefox.exe /F & taskkill /IM msedge.exe /F",
    "close_all_office": "taskkill /IM winword.exe /F & taskkill /IM excel.exe /F & taskkill /IM powerpnt.exe /F",
    "close_all_apps": "taskkill /F /FI \"STATUS eq RUNNING\"",
    "close_blender": "taskkill /IM blender.exe /F",
    "close_premiere": "taskkill /IM adobe premiere.exe /F",
    "close_aftereffects": "taskkill /IM afterfx.exe /F",
    "close_illustrator": "taskkill /IM illustrator.exe /F",
    "close_audacity": "taskkill /IM audacity.exe /F",
    "close_gimp": "taskkill /IM gimp.exe /F",
    "close_skype": "taskkill /IM skype.exe /F",
    "close_teams": "taskkill /IM teams.exe /F",
    "close_wordpad": "taskkill /IM wordpad.exe /F",
    "close_magnifier": "taskkill /IM magnify.exe /F",
    "close_narrator": "taskkill /IM narrator.exe /F",
    "close_osk": "taskkill /IM osk.exe /F",
    "close_charactermap": "taskkill /IM charmap.exe /F",
    "close_explorer": "taskkill /IM explorer.exe /F",
    
    ///// Kontrol Sistem /////
    "mute_volume": "powershell -c \"(New-Object -ComObject WScript.Shell).SendKeys([char]173)\"",
    "unmute_volume": "powershell -c \"(New-Object -ComObject WScript.Shell).SendKeys([char]173)\"",
    "volume_up": "powershell -c \"(New-Object -ComObject WScript.Shell).SendKeys([char]175)\"", 
    "volume_down": "powershell -c \"(New-Object -ComObject WScript.Shell).SendKeys([char]174)\"",
    "screenshot": "powershell -c \"Add-Type -AssemblyName System.Windows.Forms;[System.Windows.Forms.SendKeys]::SendWait('^{PRTSC}')\"",
    "rotate_screen": "powershell -c \"$rotationValue = (Get-CimInstance -Namespace root\\wmi -ClassName WmiMonitorBasicDisplayParams).CurrentRotation;if($rotationValue -eq 0){$newRotation = 1}else{$newRotation = 0};(Get-CimInstance -Namespace root\\wmi -ClassName WmiMonitorBasicDisplayParams).SetRotation($newRotation)\"",
    "monitor_off": "powershell -c \"(Add-Type '[DllImport(\"user32.dll\")]public static extern int SendMessage(int hWnd, int hMsg, int wParam, int lParam);' -Name a -Pas)::SendMessage(-1,0x0112,0xF170,2)\"",
    "empty_recycle": "rd /s /q c:\\$Recycle.bin",
    "clear_clipboard": "cmd /c \"echo off | clip\"",
    "set_volume_50": "powershell -c \"$obj = New-Object -ComObject WScript.Shell;1..52 | ForEach-Object {$obj.SendKeys([char]174)}\"",
    "set_volume_100": "powershell -c \"$obj = New-Object -ComObject WScript.Shell;1..100 | ForEach-Object {$obj.SendKeys([char]175)}\"",
    "webcam_on": "start microsoft.windows.camera:",
    "webcam_off": "taskkill /IM WindowsCamera.exe /F",
    "bluetooth_on": "powershell \"Add-Type -AssemblyName System.Runtime.WindowsRuntime;[Windows.Devices.Radios.Radio,Windows.System.Devices,ContentType=WindowsRuntime].GetMethod('RequestAccessAsync').Invoke(\$null,\$null).AsTask().Wait();[Windows.Devices.Radios.Radio]::GetDefaultAsync().AsTask().Result.SetStateAsync([Windows.Devices.Radios.RadioState]::On).AsTask().Wait()\"",
    "bluetooth_off": "powershell \"Add-Type -AssemblyName System.Runtime.WindowsRuntime;[Windows.Devices.Radios.Radio,Windows.System.Devices,ContentType=WindowsRuntime].GetMethod('RequestAccessAsync').Invoke(\$null,\$null).AsTask().Wait();[Windows.Devices.Radios.Radio]::GetDefaultAsync().AsTask().Result.SetStateAsync([Windows.Devices.Radios.RadioState]::Off).AsTask().Wait()\"",
    "wifi_on": "netsh interface set interface \"Wi-Fi\" enabled",
    "wifi_off": "netsh interface set interface \"Wi-Fi\" disabled",
    "refresh": "taskkill /F /IM explorer.exe & start explorer.exe",


    "get_system_info": "get_system_info",
    "get_installed_apps": "get_installed_apps",
    "get_running_processes": "get_running_processes",
    "close_all_apps": "close_all_apps",

    ///// Untuk system info /////
    "system_info": "start ms-settings:system",
    "cek_spesifikasi": "start ms-settings:system",
    "properties_laptop": "start ms-settings:system",
};

module.exports = commandMap;